### ISSUE TITLE
Could not connect to server

### ISSUE THREAD

**Issue by ryscript** [sstur/shopify-ftp#6] opened 2015-08-08 05:39 UTC
Status:	Connecting to 127.0.0.1:2121...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".

I'm using FTP client, Windows 10, 64 Bit Computer.

Thanks

**Comment by sstur** [comment] 2015-08-08 15:02
Which FTP client are you using?

**Comment by ryscript** [comment] 2015-08-09 13:33
Hello, thanks for the reply I'm using FileZilla FTP client.

Thanks again

**Comment by sstur** [comment] 2015-08-09 15:11
Thanks Ryan. I've not tried it on Windows 10 but I will try to reproduce this issue if I can find a Windows machine. Can you provide me any details or steps to reproduce the problem?

**Comment by ryscript** [comment] 2015-08-10 03:19
Hello, I've follow the steps you said, from creating Shopify App, UN and PW etc. 

Ryan S

**Comment by mroncetwice** [comment] 2015-09-25 20:19
Hi,
Windows 7 x64 / Filezilla also getting the same connection error.

Here's the error dump from command line:

    FTP server listening on 127.0.0.1:2121
    FTP connection from 127.0.0.1
    fetched themes
    readdir \
    undefined:0
    
    ^
    SyntaxError: Unexpected end of input
        at Object.parse (native)
        at Request._callback (C:\Users\____\AppData\Roaming\npm\node_modules\
    shopify-ftp\shopify.js:338:25)
        at Request.self.callback (C:\Users\____\AppData\Roaming\npm\node_modu
    les\shopify-ftp\node_modules\request\request.js:198:22)
        at Request.emit (events.js:110:17)
        at Request.<anonymous> (C:\Users\____\AppData\Roaming\npm\node_module
    s\shopify-ftp\node_modules\request\request.js:1063:14)
        at Request.emit (events.js:129:20)
        at IncomingMessage.<anonymous> (C:\Users\____\AppData\Roaming\npm\nod
    e_modules\shopify-ftp\node_modules\request\request.js:1009:12)
        at IncomingMessage.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)

Cheers.

**Comment by sstur** [comment] 2015-10-13 11:04
This appears to be the same error that others have been getting on Windows. Closing as duplicate of #2. I will update that issue with any fix I can find.

**Closed by sstur** 2015-10-13 11:04 UTC

**Comment by sstur** [comment] 2015-10-18 03:09
This has now been fixed! Thanks for your patience.

**Comment by ryscript** [comment] 2015-10-19 02:04
Hello, thanks for the update, okay I'll test it out, "it's better late than never" :)

Ryan S

**Comment by mroncetwice** [comment] 2015-10-21 17:24
Thank you very very much for the fix. It works without a hitch now :)

**Comment by ryscript** [comment] 2015-11-10 08:04
Perfect the update works just fine, thanks.
