### ISSUE TITLE
Could not login to FTP, got this error on terminal.

### ISSUE THREAD

**Issue by Nikschavan** [sstur/shopify-ftp#3] opened 2015-02-23 07:54 UTC
FTP server listening on 127.0.0.1:2121
FTP connection from 127.0.0.1
fetched themes
readdir \

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (C:\Program Files (x86)\shopify-ftp\node_modules\shopif
y-ftp\shopify.js:338:25)
    at Request.self.callback (C:\Program Files (x86)\shopify-ftp\node_modules\sh
opify-ftp\node_modules\request\request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Program Files (x86)\shopify-ftp\node_modules\shop
ify-ftp\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Program Files (x86)\shopify-ftp\node_modu
les\shopify-ftp\node_modules\request\request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

**Comment by sstur** [comment] 2015-10-13 11:03
This appears to be the same error that others have been getting on Windows. Closing as duplicate of #2. I will update that issue with any fix I can find.

**Closed by sstur** 2015-10-13 11:03 UTC

**Comment by sstur** [comment] 2015-10-18 03:10
This has now been fixed in the latest version. Please let me know if you run into any other issues on Windows. Thanks!
